language: node_js

git:
    depth: 1

node_js:
  - '10'

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test


cache: yarn
after_script: "cat ./coverage/lcov.info | coveralls"