version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
     - run:
          name: Install Global Dependencies
          command: yarn global add audit-ci license-checker
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Build app
          command: yarn build
      - run:
          name: Lint app
          command: yarn lint
      - run:
          name: Test app
          command: yarn test
      - run:
          name: Security autid
          command: audit-ci -m
      - run:
          name: Outdated verify
          command: yarn outdated
      - run:
          name: License verify
          command: license-checker --exclude 'MIT, MIT OR X11, BSD, ISC, CC-BY-3.0, CC-BY-4.0, Unlicense, CC0-1.0, Apache-2.0, WTFPL, MPL-2.0, Public Domain, MIT AND Zlib'