# Full Developer Environment
version: '2.2'

services:
 nginx:
    build: nginx-docker
    container_name: nginx
    ports:
      - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true